<script lang="ts">
  import { renderCommand, type Action, type ActionCreate, type ActionPatch } from '$lib/api';

  type Draft = {
    name: string;
    description: string;
    command: string;
    argsText: string;
    isAgent: boolean;
    enabled: boolean;
  };

  let {
    mode,
    source,
    saving = false,
    saveError = '',
    onSave,
    onDelete,
    onCancel
  }: {
    mode: 'create' | 'edit';
    source: Action | null;
    saving?: boolean;
    saveError?: string;
    onSave: (write: ActionCreate | ActionPatch) => void;
    onDelete: () => void;
    onCancel: () => void;
  } = $props();

  function toDraft(action: Action | null): Draft {
    return {
      name: action?.name ?? '',
      description: action?.description ?? '',
      command: action?.command ?? '',
      argsText: action?.args.join('\n') ?? '',
      isAgent: action?.isAgent ?? false,
      enabled: action?.enabled ?? true
    };
  }

  // Wrapper (not an inline call): the draft intentionally captures `source`
  // once on mount, and the function boundary keeps svelte-check from flagging
  // the initial-value read as a lost reactive reference.
  function initialDraft(): Draft {
    return toDraft(source);
  }

  let draft = $state<Draft>(initialDraft());
  let canSave = $derived(draft.name.trim() !== '' && draft.command.trim() !== '');
  let args = $derived(draft.argsText === '' ? [] : draft.argsText.split('\n'));
  let commandPreview = $derived(renderCommand(draft.command.trim() || '…', args));

  function buildWrite(): ActionCreate | ActionPatch {
    const description = draft.description.trim();
    const values = {
      name: draft.name.trim(),
      command: draft.command.trim(),
      args,
      isAgent: draft.isAgent,
      enabled: draft.enabled
    };
    if (mode === 'create') {
      return description ? { ...values, description } : values;
    }
    return { ...values, description: description || null };
  }

  function save() {
    if (!canSave || saving) return;
    onSave(buildWrite());
  }
</script>

<div
  class="scrim"
  role="button"
  tabindex="-1"
  aria-label="Close editor"
  onclick={onCancel}
  onkeydown={(event) => event.key === 'Escape' && onCancel()}
></div>
<div class="drawer" role="dialog" aria-modal="true" aria-label="Action editor">
  <div class="dhead">
    <span style="font-size:15px;font-weight:600">
      {mode === 'create' ? 'New action' : `Edit ${source?.name ?? ''}`}
    </span>
    <button class="iconbtn" style="margin-left:auto" aria-label="Close" onclick={onCancel}>✕</button>
  </div>

  <div class="dbody">
    {#if source}
      <div style="margin-bottom:14px">
        <span class="lbl">Action ID</span>
        <span class="mono" style="font-size:12px;color:var(--dc-mut)">{source.id}</span>
        <p class="hint">Generated by the server and never changes.</p>
      </div>
    {/if}

    <div style="margin-bottom:14px">
      <label class="lbl" for="ed-name">Name</label>
      <input
        id="ed-name"
        class="inp"
        value={draft.name}
        oninput={(event) => (draft.name = event.currentTarget.value)}
        placeholder="Codex"
      />
    </div>

    <div style="margin-bottom:14px">
      <label class="lbl" for="ed-desc">Description</label>
      <input
        id="ed-desc"
        class="inp"
        value={draft.description}
        oninput={(event) => (draft.description = event.currentTarget.value)}
        placeholder="What this action runs"
      />
      <p class="hint">Optional. Clearing this field removes the description.</p>
    </div>

    <div class="seclabel" style="margin:22px 0 12px">Launch command</div>
    <div style="margin-bottom:14px">
      <label class="lbl" for="ed-command">Command</label>
      <input
        id="ed-command"
        class="inp mono"
        value={draft.command}
        oninput={(event) => (draft.command = event.currentTarget.value)}
        placeholder="codex"
      />
    </div>

    <div style="margin-bottom:16px">
      <label class="lbl" for="ed-args">Arguments</label>
      <textarea
        id="ed-args"
        class="ta mono"
        value={draft.argsText}
        oninput={(event) => (draft.argsText = event.currentTarget.value)}
        placeholder={"run\ndev"}
        rows="5"
      ></textarea>
      <p class="hint">One literal argument per line. Values are never interpolated or split.</p>
    </div>

    <div
      style="display:flex;align-items:center;gap:11px;padding:12px 0;border-top:1px solid var(--dc-bd)"
    >
      <div style="flex:1">
        <div style="font-size:13px;font-weight:500">Agent</div>
        <p class="hint">Classify sessions from this action as coding-agent sessions.</p>
      </div>
      <input
        id="ed-agent"
        type="checkbox"
        checked={draft.isAgent}
        onchange={(event) => (draft.isAgent = event.currentTarget.checked)}
      />
    </div>

    <div
      style="display:flex;align-items:center;gap:11px;padding:12px 0;border-top:1px solid var(--dc-bd);border-bottom:1px solid var(--dc-bd)"
    >
      <div style="flex:1">
        <div style="font-size:13px;font-weight:500">Enabled</div>
        <p class="hint">Disabled actions remain visible but cannot start new sessions.</p>
      </div>
      <button
        class="switch"
        class:on={draft.enabled}
        aria-label="Toggle enabled"
        aria-pressed={draft.enabled}
        onclick={() => (draft.enabled = !draft.enabled)}
      >
        <span class="knob"></span>
      </button>
    </div>

    <div class="seclabel" style="margin:22px 0 10px">Command preview</div>
    <div class="codeblock">
      <span class="code"><span style="color:var(--dc-green)">$</span> {commandPreview}</span>
    </div>

    {#if saveError}
      <div
        class="card"
        style="border-color:color-mix(in srgb,var(--dc-red) 40%,transparent);background:color-mix(in srgb,var(--dc-red) 10%,transparent);color:var(--dc-red);padding:10px 14px;margin-top:16px;font-size:12.5px"
      >
        {saveError}
      </div>
    {/if}
  </div>

  <div class="dfoot">
    {#if mode === 'edit'}
      <button
        class="btn"
        style="color:var(--dc-red);border-color:color-mix(in srgb,var(--dc-red) 40%,transparent)"
        onclick={onDelete}
        disabled={saving}
      >
        Delete
      </button>
    {/if}
    <button class="btn ghost" style="margin-left:auto" onclick={onCancel} disabled={saving}>
      Cancel
    </button>
    <button class="btn primary" class:off={!canSave} disabled={!canSave || saving} onclick={save}>
      {saving ? 'Saving…' : mode === 'create' ? 'Create action' : 'Save changes'}
    </button>
  </div>
</div>
