#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Dev runs a hermetic profile under tmp/dev/: its own config, loopback bind,
# Unix socket, database, and actions file. Your personal Atelier Code config
# (~/.config/atc/atc.toml) and ATC_* environment overrides never
# apply here, and the dedicated port keeps dev clear of a background service
# on the default 7331. Delete tmp/dev for a fresh dev state.
DEV_DIR="$ROOT/tmp/dev"
DEV_CONFIG="$DEV_DIR/atc.toml"
API_ADDR="127.0.0.1:7332"
API_PORT="${API_ADDR##*:}"
API_URL="http://$API_ADDR"
WEB_PORT="5173"
WEB_URL="http://127.0.0.1:$WEB_PORT"

API_PID=""
WEB_PID=""
CLEANED_UP=0

usage() {
  cat <<EOF
usage: tools/dev.sh

Starts the Atelier Code API and Vite web server in the foreground, isolated from
any installed Atelier Code service (state lives in tmp/dev/).
Stop both processes with Ctrl-C.
EOF
}

write_dev_config() {
  mkdir -p "$DEV_DIR"
  cat > "$DEV_CONFIG" <<EOF
# Generated by tools/dev.sh on every run — edits here are overwritten.
# The Vite dev proxy in web/vite.config.ts targets the same address.

[server]
http_addr = "$API_ADDR"

[paths]
control_dir = "$DEV_DIR"

[store]
db_path = "$DEV_DIR/atc.db"
EOF
}

port_in_use() {
  local port="$1"

  if command -v ss >/dev/null 2>&1; then
    ss -H -ltn "sport = :$port" 2>/dev/null | grep -q .
    return
  fi

  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN -t 2>/dev/null | grep -q .
    return
  fi

  return 1
}

show_port_owner() {
  local port="$1"

  if command -v ss >/dev/null 2>&1; then
    ss -ltnp "sport = :$port" >&2 || true
    return
  fi

  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN >&2 || true
  fi
}

require_port_free() {
  local name="$1"
  local port="$2"

  if port_in_use "$port"; then
    echo "$name port $port is already in use" >&2
    show_port_owner "$port"
    exit 1
  fi
}

prefix() {
  local name="$1"
  local line

  while IFS= read -r line || [ -n "$line" ]; do
    printf '[%s] %s\n' "$name" "$line"
  done
}

process_running() {
  local pid="$1"
  [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null
}

tree_pids() {
  local pid="$1"
  local child

  for child in $(pgrep -P "$pid" 2>/dev/null || true); do
    tree_pids "$child"
  done
  printf '%s\n' "$pid"
}

collect_tree_pids() {
  local pid="$1"
  local child
  local pids=()

  while IFS= read -r child; do
    if [ -n "$child" ]; then
      pids+=("$child")
    fi
  done < <(tree_pids "$pid")

  printf '%s\n' "${pids[@]}"
}

any_running() {
  local pid

  for pid in "$@"; do
    if process_running "$pid"; then
      return 0
    fi
  done
  return 1
}

wait_for_http() {
  local name="$1"
  local url="$2"
  local pid="$3"
  local i

  for i in {1..80}; do
    if ! process_running "$pid"; then
      echo "$name exited before becoming ready" >&2
      return 1
    fi
    if curl -fsS --max-time 1 "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.25
  done

  echo "$name did not become ready at $url" >&2
  return 1
}

wait_for_first_exit() {
  while any_running "$API_PID" "$WEB_PID"; do
    if ! process_running "$API_PID"; then
      wait "$API_PID"
      return "$?"
    fi
    if ! process_running "$WEB_PID"; then
      wait "$WEB_PID"
      return "$?"
    fi
    sleep 0.25
  done

  return 0
}

stop_process() {
  local name="$1"
  local pid="$2"
  local signal="${3:-TERM}"
  local pids=()
  local child

  if ! process_running "$pid"; then
    return 0
  fi

  while IFS= read -r child; do
    if [ -n "$child" ]; then
      pids+=("$child")
    fi
  done < <(collect_tree_pids "$pid")

  if [ "${#pids[@]}" -eq 0 ]; then
    return 0
  fi

  echo "Stopping $name..."
  for child in "${pids[@]}"; do
    kill "-$signal" "$child" 2>/dev/null || true
  done

  local i
  for i in {1..40}; do
    if ! any_running "${pids[@]}"; then
      return 0
    fi
    sleep 0.125
  done

  echo "$name did not stop after TERM; sending KILL"
  for child in "${pids[@]}"; do
    kill -KILL "$child" 2>/dev/null || true
  done
}

cleanup() {
  local signal="${1:-TERM}"

  if [ "$CLEANED_UP" -eq 1 ]; then
    return 0
  fi
  CLEANED_UP=1

  stop_process "Vite dev server" "$WEB_PID" "$signal"
  stop_process "Atelier Code API" "$API_PID" "$signal"
}

on_signal() {
  local signal="${1:-TERM}"

  echo
  cleanup "$signal"
  exit 0
}

start_api() {
  # Clear personal ATC_* overrides (empty means unset to config.Load) so
  # the generated dev config is the only source of truth. ATC_ZMX_BIN
  # stays honored — it locates a tool, not state.
  bash -c '
    cd "$1"
    export ATC_CONFIG= ATC_HTTP_ADDR= ATC_DB_PATH= ATC_ACTIONS_PATH= ATC_API_TOKEN=
    exec go run ./cmd/atc serve --config "$2"
  ' bash "$ROOT" "$DEV_CONFIG" \
    > >(prefix api) 2>&1 &
  API_PID="$!"
}

start_web() {
  bash -c '
    cd "$1/web"
    pnpm install
    exec pnpm dev
  ' bash "$ROOT" \
    > >(prefix web) 2>&1 &
  WEB_PID="$!"
}

main() {
  if [ "$#" -ne 0 ]; then
    usage >&2
    exit 2
  fi

  require_port_free "Atelier Code API" "$API_PORT"
  require_port_free "Vite web" "$WEB_PORT"

  trap 'on_signal HUP' HUP
  trap 'on_signal INT' INT
  trap 'on_signal TERM' TERM
  trap cleanup EXIT

  echo "Starting Atelier Code dev..."
  write_dev_config
  start_api
  start_web

  if ! wait_for_http "Atelier Code API" "$API_URL/api/health" "$API_PID"; then
    exit 1
  fi
  if ! wait_for_http "Vite dev server" "$WEB_URL/" "$WEB_PID"; then
    exit 1
  fi

  cat <<EOF
Atelier Code dev ready
UI:    $WEB_URL
API:   $API_URL
State: tmp/dev (delete for a fresh dev database)
CLI:   go run ./cmd/atc --config tmp/dev/atc.toml sessions list
Stop:  Ctrl-C

Logs:
EOF

  local status=0
  wait_for_first_exit || status="$?"
  cleanup
  wait "$API_PID" 2>/dev/null || true
  wait "$WEB_PID" 2>/dev/null || true
  exit "$status"
}

main "$@"
