enum CommandID: String, CaseIterable, Sendable {
    case toggleSidebar = "view.toggle-sidebar"
    case toggleCommandPalette = "view.toggle-command-palette"
    case searchSessions = "view.search-sessions"
    case searchTerminals = "view.search-terminals"
    case searchWorkspaces = "view.search-workspaces"
    case showDashboard = "view.show-dashboard"
    case newSession = "session.new"
    case newTerminal = "terminal.new"
    case newProject = "project.new"
    case newWorkspace = "workspace.new"
    case refresh = "data.refresh"
    case reloadConfiguration = "configuration.reload"
    case revealConfiguration = "configuration.reveal"
}
