// Regenerates src/adminUi/manifest.generated.ts from the committed admin UI
// build (web/build). The manifest imports every asset with Bun's
// `{ type: "file" }` attribute, which is what embeds the files into the
// compiled executable — `bun build --compile` follows the imports and packs
// the referenced files. `--check` fails when the manifest is stale relative
// to web/build (the drift gate wired into `mise run check`).
//
// Usage: bun run scripts/adminAssets.ts [--check]
import { fileURLToPath } from "node:url"

const root = new URL("..", import.meta.url)
const buildDir = fileURLToPath(new URL("web/build/", root))
const manifestFile = new URL("src/adminUi/manifest.generated.ts", root)

const files: string[] = []
try {
  for await (const path of new Bun.Glob("**/*").scan({ cwd: buildDir, onlyFiles: true })) {
    files.push(path)
  }
} catch {
  // fall through to the empty-list diagnostic
}
files.sort()

if (files.length === 0) {
  console.error(`no admin UI build found in ${buildDir} — run \`mise run web:build\` first`)
  process.exit(1)
}

const lines = [
  "// Generated by scripts/adminAssets.ts from web/build — do not edit.",
  '// Each `type: "file"` import resolves to a path servable with Bun.file():',
  "// the file itself on a source run, an embedded file in a compiled binary.",
  "// The asset modules have no types (and project-global wildcard ambients",
  "// would suppress real missing-module errors), so checking is off for this",
  "// file; consumers type against the export annotation, and a missing file",
  "// still fails the compile because Bun resolves the imports at bundle time.",
  "// @ts-nocheck",
  ...files.map(
    (file, index) =>
      `import f${index} from ${JSON.stringify(`../../web/build/${file}`)} with { type: "file" }`,
  ),
  "",
  "export const assets: ReadonlyArray<readonly [string, string]> = [",
  ...files.map((file, index) => `  [${JSON.stringify(file)}, f${index}],`),
  "]",
  "",
]
const manifest = lines.join("\n")

if (process.argv.includes("--check")) {
  const existing = await Bun.file(manifestFile)
    .text()
    .catch(() => "")
  if (existing !== manifest) {
    console.error("src/adminUi/manifest.generated.ts is stale — run `mise run web:build`")
    process.exit(1)
  }
  process.exit(0)
}

await Bun.write(manifestFile, manifest)
console.log(`wrote manifest for ${files.length} assets`)
