// Generated by scripts/adminAssets.ts from web/build — do not edit.
// Each `type: "file"` import resolves to a path servable with Bun.file():
// the file itself on a source run, an embedded file in a compiled binary.
// The asset modules have no types (and project-global wildcard ambients
// would suppress real missing-module errors), so checking is off for this
// file; consumers type against the export annotation, and a missing file
// still fails the compile because Bun resolves the imports at bundle time.
// @ts-nocheck
import f0 from "../../web/build/_app/immutable/assets/0.Dus0i3hQ.css" with { type: "file" }
import f1 from "../../web/build/_app/immutable/assets/3.Bhc8lHrM.css" with { type: "file" }
import f2 from "../../web/build/_app/immutable/chunks/2yBSykYL.js" with { type: "file" }
import f3 from "../../web/build/_app/immutable/chunks/3BiiUL6x.js" with { type: "file" }
import f4 from "../../web/build/_app/immutable/chunks/46pUO-KZ.js" with { type: "file" }
import f5 from "../../web/build/_app/immutable/chunks/6eiFfrIK2.js" with { type: "file" }
import f6 from "../../web/build/_app/immutable/chunks/7d0kWrxk.js" with { type: "file" }
import f7 from "../../web/build/_app/immutable/chunks/8awoKsRr.js" with { type: "file" }
import f8 from "../../web/build/_app/immutable/chunks/B2Hk0byY.js" with { type: "file" }
import f9 from "../../web/build/_app/immutable/chunks/B5MOuGk22.js" with { type: "file" }
import f10 from "../../web/build/_app/immutable/chunks/BErptJQt2.js" with { type: "file" }
import f11 from "../../web/build/_app/immutable/chunks/BFWuos0b2.js" with { type: "file" }
import f12 from "../../web/build/_app/immutable/chunks/BIfVWKek2.js" with { type: "file" }
import f13 from "../../web/build/_app/immutable/chunks/BJ_DvF2z2.js" with { type: "file" }
import f14 from "../../web/build/_app/immutable/chunks/BP3yBJPd2.js" with { type: "file" }
import f15 from "../../web/build/_app/immutable/chunks/BSIfJ5Lf2.js" with { type: "file" }
import f16 from "../../web/build/_app/immutable/chunks/BUw5BFEQ2.js" with { type: "file" }
import f17 from "../../web/build/_app/immutable/chunks/BbMFWNh2.js" with { type: "file" }
import f18 from "../../web/build/_app/immutable/chunks/Bf9gth62.js" with { type: "file" }
import f19 from "../../web/build/_app/immutable/chunks/Bg1pJEfF.js" with { type: "file" }
import f20 from "../../web/build/_app/immutable/chunks/Bjk68DPx.js" with { type: "file" }
import f21 from "../../web/build/_app/immutable/chunks/Bjy-W4x2.js" with { type: "file" }
import f22 from "../../web/build/_app/immutable/chunks/BmcBoeu_2.js" with { type: "file" }
import f23 from "../../web/build/_app/immutable/chunks/BnBcQDk8.js" with { type: "file" }
import f24 from "../../web/build/_app/immutable/chunks/Bux9G6xp.js" with { type: "file" }
import f25 from "../../web/build/_app/immutable/chunks/BwhffYGR.js" with { type: "file" }
import f26 from "../../web/build/_app/immutable/chunks/Bx7GMTLj.js" with { type: "file" }
import f27 from "../../web/build/_app/immutable/chunks/BxGV6wVB2.js" with { type: "file" }
import f28 from "../../web/build/_app/immutable/chunks/BxGiN3sx.js" with { type: "file" }
import f29 from "../../web/build/_app/immutable/chunks/Bxn0AqGG.js" with { type: "file" }
import f30 from "../../web/build/_app/immutable/chunks/BzCF02fh.js" with { type: "file" }
import f31 from "../../web/build/_app/immutable/chunks/C-4yloiy.js" with { type: "file" }
import f32 from "../../web/build/_app/immutable/chunks/C0p62JRo.js" with { type: "file" }
import f33 from "../../web/build/_app/immutable/chunks/C15dDins.js" with { type: "file" }
import f34 from "../../web/build/_app/immutable/chunks/C1AQfcnw.js" with { type: "file" }
import f35 from "../../web/build/_app/immutable/chunks/C3MuqjTs.js" with { type: "file" }
import f36 from "../../web/build/_app/immutable/chunks/CBnasP7H.js" with { type: "file" }
import f37 from "../../web/build/_app/immutable/chunks/CELxpiQF2.js" with { type: "file" }
import f38 from "../../web/build/_app/immutable/chunks/CINElORr.js" with { type: "file" }
import f39 from "../../web/build/_app/immutable/chunks/CK8Nh64t.js" with { type: "file" }
import f40 from "../../web/build/_app/immutable/chunks/COtxw2HO2.js" with { type: "file" }
import f41 from "../../web/build/_app/immutable/chunks/CPbLOOA8.js" with { type: "file" }
import f42 from "../../web/build/_app/immutable/chunks/CZ2Hln1m2.js" with { type: "file" }
import f43 from "../../web/build/_app/immutable/chunks/CZPspivy2.js" with { type: "file" }
import f44 from "../../web/build/_app/immutable/chunks/CdBf1tLT2.js" with { type: "file" }
import f45 from "../../web/build/_app/immutable/chunks/CjsGlIR72.js" with { type: "file" }
import f46 from "../../web/build/_app/immutable/chunks/CjvKhpDE2.js" with { type: "file" }
import f47 from "../../web/build/_app/immutable/chunks/ClsvP8HF.js" with { type: "file" }
import f48 from "../../web/build/_app/immutable/chunks/Cn5xxuEO.js" with { type: "file" }
import f49 from "../../web/build/_app/immutable/chunks/CnyYCzxB.js" with { type: "file" }
import f50 from "../../web/build/_app/immutable/chunks/CoHD0tBY2.js" with { type: "file" }
import f51 from "../../web/build/_app/immutable/chunks/Crwqk5oE.js" with { type: "file" }
import f52 from "../../web/build/_app/immutable/chunks/CsizH9XH.js" with { type: "file" }
import f53 from "../../web/build/_app/immutable/chunks/Ct1nwDAi.js" with { type: "file" }
import f54 from "../../web/build/_app/immutable/chunks/CwutpoyX.js" with { type: "file" }
import f55 from "../../web/build/_app/immutable/chunks/CzbI9yt8.js" with { type: "file" }
import f56 from "../../web/build/_app/immutable/chunks/D0mF0s4W.js" with { type: "file" }
import f57 from "../../web/build/_app/immutable/chunks/D3wp9A-z.js" with { type: "file" }
import f58 from "../../web/build/_app/immutable/chunks/D49C9JLl.js" with { type: "file" }
import f59 from "../../web/build/_app/immutable/chunks/DAUq3v8d.js" with { type: "file" }
import f60 from "../../web/build/_app/immutable/chunks/DCsk4CA5.js" with { type: "file" }
import f61 from "../../web/build/_app/immutable/chunks/DEkwSfJ8.js" with { type: "file" }
import f62 from "../../web/build/_app/immutable/chunks/DG1ZNoOB.js" with { type: "file" }
import f63 from "../../web/build/_app/immutable/chunks/DK3Fl9T5.js" with { type: "file" }
import f64 from "../../web/build/_app/immutable/chunks/DKEmTYwX.js" with { type: "file" }
import f65 from "../../web/build/_app/immutable/chunks/DMPWMJy8.js" with { type: "file" }
import f66 from "../../web/build/_app/immutable/chunks/DOQpPQar.js" with { type: "file" }
import f67 from "../../web/build/_app/immutable/chunks/DP4kimYU2.js" with { type: "file" }
import f68 from "../../web/build/_app/immutable/chunks/DPYbWc5v2.js" with { type: "file" }
import f69 from "../../web/build/_app/immutable/chunks/DQzAqUAt.js" with { type: "file" }
import f70 from "../../web/build/_app/immutable/chunks/DS12RZVF.js" with { type: "file" }
import f71 from "../../web/build/_app/immutable/chunks/DTdCRJhE2.js" with { type: "file" }
import f72 from "../../web/build/_app/immutable/chunks/DZAOF76O.js" with { type: "file" }
import f73 from "../../web/build/_app/immutable/chunks/Db5S8dkt.js" with { type: "file" }
import f74 from "../../web/build/_app/immutable/chunks/DdrML4s_.js" with { type: "file" }
import f75 from "../../web/build/_app/immutable/chunks/DgjDowub.js" with { type: "file" }
import f76 from "../../web/build/_app/immutable/chunks/DhXtBWiR.js" with { type: "file" }
import f77 from "../../web/build/_app/immutable/chunks/DmPgvIga2.js" with { type: "file" }
import f78 from "../../web/build/_app/immutable/chunks/DmgjYHV22.js" with { type: "file" }
import f79 from "../../web/build/_app/immutable/chunks/Do3ZPaSv.js" with { type: "file" }
import f80 from "../../web/build/_app/immutable/chunks/H5zdc2lY.js" with { type: "file" }
import f81 from "../../web/build/_app/immutable/chunks/HD2cj2NY.js" with { type: "file" }
import f82 from "../../web/build/_app/immutable/chunks/HclGiUj8.js" with { type: "file" }
import f83 from "../../web/build/_app/immutable/chunks/RTDZ46NG2.js" with { type: "file" }
import f84 from "../../web/build/_app/immutable/chunks/RiUH-ovk.js" with { type: "file" }
import f85 from "../../web/build/_app/immutable/chunks/Rwccrh7Z.js" with { type: "file" }
import f86 from "../../web/build/_app/immutable/chunks/Vgyr6pK82.js" with { type: "file" }
import f87 from "../../web/build/_app/immutable/chunks/d3CDMy7g.js" with { type: "file" }
import f88 from "../../web/build/_app/immutable/chunks/ex4JdpDM.js" with { type: "file" }
import f89 from "../../web/build/_app/immutable/chunks/ghBTFsGM.js" with { type: "file" }
import f90 from "../../web/build/_app/immutable/chunks/kq4-6Ky_.js" with { type: "file" }
import f91 from "../../web/build/_app/immutable/chunks/lzmJlvK-.js" with { type: "file" }
import f92 from "../../web/build/_app/immutable/chunks/q9b-YUin2.js" with { type: "file" }
import f93 from "../../web/build/_app/immutable/chunks/uF3AVkAk.js" with { type: "file" }
import f94 from "../../web/build/_app/immutable/chunks/ub1C_b-Z.js" with { type: "file" }
import f95 from "../../web/build/_app/immutable/chunks/v7gG-aIR2.js" with { type: "file" }
import f96 from "../../web/build/_app/immutable/chunks/xihTtKlq.js" with { type: "file" }
import f97 from "../../web/build/_app/immutable/chunks/y9QvO_c7.js" with { type: "file" }
import f98 from "../../web/build/_app/immutable/chunks/yK8eDM9O2.js" with { type: "file" }
import f99 from "../../web/build/_app/immutable/entry/app.CW7mFuyn.js" with { type: "file" }
import f100 from "../../web/build/_app/immutable/entry/start.D3zy27hh.js" with { type: "file" }
import f101 from "../../web/build/_app/immutable/nodes/0.BXhiZiaM.js" with { type: "file" }
import f102 from "../../web/build/_app/immutable/nodes/1.BiwH9Kwz.js" with { type: "file" }
import f103 from "../../web/build/_app/immutable/nodes/2.DTSATyNA.js" with { type: "file" }
import f104 from "../../web/build/_app/immutable/nodes/3.Cb33CR-T.js" with { type: "file" }
import f105 from "../../web/build/_app/version.json" with { type: "file" }
import f106 from "../../web/build/docs.html" with { type: "file" }
import f107 from "../../web/build/favicon.svg" with { type: "file" }
import f108 from "../../web/build/index.html" with { type: "file" }

export const assets: ReadonlyArray<readonly [string, string]> = [
  ["_app/immutable/assets/0.Dus0i3hQ.css", f0],
  ["_app/immutable/assets/3.Bhc8lHrM.css", f1],
  ["_app/immutable/chunks/2yBSykYL.js", f2],
  ["_app/immutable/chunks/3BiiUL6x.js", f3],
  ["_app/immutable/chunks/46pUO-KZ.js", f4],
  ["_app/immutable/chunks/6eiFfrIK2.js", f5],
  ["_app/immutable/chunks/7d0kWrxk.js", f6],
  ["_app/immutable/chunks/8awoKsRr.js", f7],
  ["_app/immutable/chunks/B2Hk0byY.js", f8],
  ["_app/immutable/chunks/B5MOuGk22.js", f9],
  ["_app/immutable/chunks/BErptJQt2.js", f10],
  ["_app/immutable/chunks/BFWuos0b2.js", f11],
  ["_app/immutable/chunks/BIfVWKek2.js", f12],
  ["_app/immutable/chunks/BJ_DvF2z2.js", f13],
  ["_app/immutable/chunks/BP3yBJPd2.js", f14],
  ["_app/immutable/chunks/BSIfJ5Lf2.js", f15],
  ["_app/immutable/chunks/BUw5BFEQ2.js", f16],
  ["_app/immutable/chunks/BbMFWNh2.js", f17],
  ["_app/immutable/chunks/Bf9gth62.js", f18],
  ["_app/immutable/chunks/Bg1pJEfF.js", f19],
  ["_app/immutable/chunks/Bjk68DPx.js", f20],
  ["_app/immutable/chunks/Bjy-W4x2.js", f21],
  ["_app/immutable/chunks/BmcBoeu_2.js", f22],
  ["_app/immutable/chunks/BnBcQDk8.js", f23],
  ["_app/immutable/chunks/Bux9G6xp.js", f24],
  ["_app/immutable/chunks/BwhffYGR.js", f25],
  ["_app/immutable/chunks/Bx7GMTLj.js", f26],
  ["_app/immutable/chunks/BxGV6wVB2.js", f27],
  ["_app/immutable/chunks/BxGiN3sx.js", f28],
  ["_app/immutable/chunks/Bxn0AqGG.js", f29],
  ["_app/immutable/chunks/BzCF02fh.js", f30],
  ["_app/immutable/chunks/C-4yloiy.js", f31],
  ["_app/immutable/chunks/C0p62JRo.js", f32],
  ["_app/immutable/chunks/C15dDins.js", f33],
  ["_app/immutable/chunks/C1AQfcnw.js", f34],
  ["_app/immutable/chunks/C3MuqjTs.js", f35],
  ["_app/immutable/chunks/CBnasP7H.js", f36],
  ["_app/immutable/chunks/CELxpiQF2.js", f37],
  ["_app/immutable/chunks/CINElORr.js", f38],
  ["_app/immutable/chunks/CK8Nh64t.js", f39],
  ["_app/immutable/chunks/COtxw2HO2.js", f40],
  ["_app/immutable/chunks/CPbLOOA8.js", f41],
  ["_app/immutable/chunks/CZ2Hln1m2.js", f42],
  ["_app/immutable/chunks/CZPspivy2.js", f43],
  ["_app/immutable/chunks/CdBf1tLT2.js", f44],
  ["_app/immutable/chunks/CjsGlIR72.js", f45],
  ["_app/immutable/chunks/CjvKhpDE2.js", f46],
  ["_app/immutable/chunks/ClsvP8HF.js", f47],
  ["_app/immutable/chunks/Cn5xxuEO.js", f48],
  ["_app/immutable/chunks/CnyYCzxB.js", f49],
  ["_app/immutable/chunks/CoHD0tBY2.js", f50],
  ["_app/immutable/chunks/Crwqk5oE.js", f51],
  ["_app/immutable/chunks/CsizH9XH.js", f52],
  ["_app/immutable/chunks/Ct1nwDAi.js", f53],
  ["_app/immutable/chunks/CwutpoyX.js", f54],
  ["_app/immutable/chunks/CzbI9yt8.js", f55],
  ["_app/immutable/chunks/D0mF0s4W.js", f56],
  ["_app/immutable/chunks/D3wp9A-z.js", f57],
  ["_app/immutable/chunks/D49C9JLl.js", f58],
  ["_app/immutable/chunks/DAUq3v8d.js", f59],
  ["_app/immutable/chunks/DCsk4CA5.js", f60],
  ["_app/immutable/chunks/DEkwSfJ8.js", f61],
  ["_app/immutable/chunks/DG1ZNoOB.js", f62],
  ["_app/immutable/chunks/DK3Fl9T5.js", f63],
  ["_app/immutable/chunks/DKEmTYwX.js", f64],
  ["_app/immutable/chunks/DMPWMJy8.js", f65],
  ["_app/immutable/chunks/DOQpPQar.js", f66],
  ["_app/immutable/chunks/DP4kimYU2.js", f67],
  ["_app/immutable/chunks/DPYbWc5v2.js", f68],
  ["_app/immutable/chunks/DQzAqUAt.js", f69],
  ["_app/immutable/chunks/DS12RZVF.js", f70],
  ["_app/immutable/chunks/DTdCRJhE2.js", f71],
  ["_app/immutable/chunks/DZAOF76O.js", f72],
  ["_app/immutable/chunks/Db5S8dkt.js", f73],
  ["_app/immutable/chunks/DdrML4s_.js", f74],
  ["_app/immutable/chunks/DgjDowub.js", f75],
  ["_app/immutable/chunks/DhXtBWiR.js", f76],
  ["_app/immutable/chunks/DmPgvIga2.js", f77],
  ["_app/immutable/chunks/DmgjYHV22.js", f78],
  ["_app/immutable/chunks/Do3ZPaSv.js", f79],
  ["_app/immutable/chunks/H5zdc2lY.js", f80],
  ["_app/immutable/chunks/HD2cj2NY.js", f81],
  ["_app/immutable/chunks/HclGiUj8.js", f82],
  ["_app/immutable/chunks/RTDZ46NG2.js", f83],
  ["_app/immutable/chunks/RiUH-ovk.js", f84],
  ["_app/immutable/chunks/Rwccrh7Z.js", f85],
  ["_app/immutable/chunks/Vgyr6pK82.js", f86],
  ["_app/immutable/chunks/d3CDMy7g.js", f87],
  ["_app/immutable/chunks/ex4JdpDM.js", f88],
  ["_app/immutable/chunks/ghBTFsGM.js", f89],
  ["_app/immutable/chunks/kq4-6Ky_.js", f90],
  ["_app/immutable/chunks/lzmJlvK-.js", f91],
  ["_app/immutable/chunks/q9b-YUin2.js", f92],
  ["_app/immutable/chunks/uF3AVkAk.js", f93],
  ["_app/immutable/chunks/ub1C_b-Z.js", f94],
  ["_app/immutable/chunks/v7gG-aIR2.js", f95],
  ["_app/immutable/chunks/xihTtKlq.js", f96],
  ["_app/immutable/chunks/y9QvO_c7.js", f97],
  ["_app/immutable/chunks/yK8eDM9O2.js", f98],
  ["_app/immutable/entry/app.CW7mFuyn.js", f99],
  ["_app/immutable/entry/start.D3zy27hh.js", f100],
  ["_app/immutable/nodes/0.BXhiZiaM.js", f101],
  ["_app/immutable/nodes/1.BiwH9Kwz.js", f102],
  ["_app/immutable/nodes/2.DTSATyNA.js", f103],
  ["_app/immutable/nodes/3.Cb33CR-T.js", f104],
  ["_app/version.json", f105],
  ["docs.html", f106],
  ["favicon.svg", f107],
  ["index.html", f108],
]
